sudo: required
services: 
  - docker

before_install: 
  - docker build -t suhasbansude/docker-react -f Dockerfile.dev . 

script:
  - docker run -e CI=true suhasbansude/docker-react npm run test
  

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker"
  evn: "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-2-474657819690"
  bucket_path: "docker"
  on: 
    branch: master
  access_key_id:
    secure: "$AWS_ACCESS_KEY" 
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
