sudo: required
services: 
  - docker

before_install: 
  - docker build -t suhasbansude/docker-react -f Dockerfile.dev . 

script:
  - docker run -e CI=true suhasbansude/docker-react npm run test
  

